### ISSUE TITLE
Sign-in cut off on medium-wide screens

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/global-nav#229] opened 2019-04-16 20:46 UTC
From a screen width of 1024px to 1302px, inclusively, something in the display is wider than the screen.  A horizontal scrollbar appears and the sign-in button and box are cut off:
![image](https://user-images.githubusercontent.com/2125181/56242856-0c349900-604e-11e9-985b-e6e774443b72.png)

This only occurs in [web mode](https://esri.github.io/global-nav/esri-global-nav.html); [app mode](https://esri.github.io/global-nav/app-mode-nav.html) has a superfluous horizontal scrollbar between 1201px to 1302px, inclusively, but it appears to be harmless.

Demos use version 1.2.1

**Comment by paulcpederson** [comment] 2020-08-17 18:03
This was caused by a hidden element overflowing the window on the x axis. I've constrained the header to `100vw` which solves the menu being cutoff.

#314

**Comment by paulcpederson** [comment] 2020-08-17 19:13
Should be fixed in [📦  v1.4.0](https://github.com/Esri/global-nav/releases/tag/v1.4.0)

**Closed by paulcpederson** 2020-08-17 19:13 UTC
Labels: 2 - In Development, bug
